services:
  frontend:
    container_name: strengthTracker-front-dev
    build:
      context: ./frontend
      dockerfile: frontend.dockerfile
    ports:
      - "4200:4200"
    volumes:
      - ./frontend/src:/app/src
      - /app/node_modules
    restart: always
    depends_on:
      - backend
    networks:
      - strengthTracker-network

  backend:
    container_name: strengthTracker-back-dev
    build:
      context: ./backend
      dockerfile: backend.dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - DB_URL=${DB_URL}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}

      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRATION=${JWT_EXPIRATION}
    volumes:
      - ./backend/src:/app/src
      - /app/node_modules
    restart: always
    depends_on:
      - db
    networks:
      - strengthTracker-network
  db:
    container_name: strengthTracker-db-dev
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - strengthTracker-network

volumes:
  pgdata:
    name: strengthTracker-pgdata

networks:
  strengthTracker-network:
