name: Lint Commit Messages

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: wagoid/commitlint-github-action@v3
